import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "./providers/MySessionProvider";
import WishlistContextProvider from "./providers/wishlistContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      
      >

        <MySessionProvider>
          <WishlistContextProvider>
        <Navbar/>
          <Toaster/>
       <div className="pt-20">
  {children}
</div>
  </WishlistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
